import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  script: string;
  direction: 'ltr' | 'rtl';
  region: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', script: 'Latin', direction: 'ltr', region: 'Global' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'Devanagari', direction: 'ltr', region: 'North India' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', script: 'Oriya', direction: 'ltr', region: 'East India' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', script: 'Bengali', direction: 'ltr', region: 'East India' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', script: 'Tamil', direction: 'ltr', region: 'South India' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', script: 'Telugu', direction: 'ltr', region: 'South India' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'Gujarati', direction: 'ltr', region: 'West India' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', script: 'Devanagari', direction: 'ltr', region: 'West India' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', script: 'Kannada', direction: 'ltr', region: 'South India' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', script: 'Gurmukhi', direction: 'ltr', region: 'North India' }
];

const translations: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    india: 'India',
    world: 'World',
    business: 'Business',
    technology: 'Technology',
    sports: 'Sports',
    entertainment: 'Entertainment',
    health: 'Health',
    breakingNews: 'Breaking News',
    featuredStories: 'Featured Stories',
    searchPlaceholder: 'Search news across categories...',
    readMore: 'Read More',
    readFull: 'Read Full Article',
    listen: 'Listen',
    share: 'Share',
    loading: 'Loading latest news...',
    noArticles: 'No articles found',
    askQuestion: 'Ask me about any news topic...',
    chatWithAI: 'Chat with AI Assistant',
    liveUpdates: 'Live Updates',
    premiumContent: 'Premium Content',
    freeContent: 'Free Access',
    trending: 'Trending Now',
    latest: 'Latest News',
    author: 'Author',
    source: 'Source',
    publishedOn: 'Published on',
    readTime: 'min read',
    tags: 'Tags',
    relatedNews: 'Related News',
    viewAll: 'View All',
    refresh: 'Refresh',
    totalArticles: 'Total Articles',
    categories: 'Categories',
    languages: 'Languages',
    realTimeUpdates: 'Real-time Updates',
    newsPortal: 'News Portal',
    todaysNews: 'Today\'s News',
    localNews: 'Local News',
    nationalNews: 'National News',
    internationalNews: 'International News',
    exclusiveReport: 'Exclusive Report',
    liveReporting: 'Live Reporting',
    newsAlert: 'News Alert',
    pressRelease: 'Press Release',
    editorial: 'Editorial',
    opinion: 'Opinion',
    analysis: 'Analysis',
    interview: 'Interview',
    photoStory: 'Photo Story',
    videoNews: 'Video News',
    podcast: 'Podcast',
    newsletter: 'Newsletter'
  },
  hi: {
    home: 'मुख्य',
    india: 'भारत',
    world: 'विश्व',
    business: 'व्यापार',
    technology: 'तकनीक',
    sports: 'खेल',
    entertainment: 'मनोरंजन',
    health: 'स्वास्थ्य',
    breakingNews: 'ताज़ा खबर',
    featuredStories: 'मुख्य समाचार',
    searchPlaceholder: 'समाचार खोजें...',
    readMore: 'और पढ़ें',
    readFull: 'पूरा लेख पढ़ें',
    listen: 'सुनें',
    share: 'साझा करें',
    loading: 'नवीनतम समाचार लोड हो रहे हैं...',
    noArticles: 'कोई लेख नहीं मिला',
    askQuestion: 'किसी भी समाचार विषय के बारे में पूछें...',
    chatWithAI: 'AI सहायक से बात करें',
    liveUpdates: 'लाइव अपडेट',
    premiumContent: 'प्रीमियम सामग्री',
    freeContent: 'निःशुल्क पहुंच',
    trending: 'ट्रेंडिंग',
    latest: 'नवीनतम समाचार',
    author: 'लेखक',
    source: 'स्रोत',
    publishedOn: 'प्रकाशित',
    readTime: 'मिनट पढ़ें',
    tags: 'टैग',
    relatedNews: 'संबंधित समाचार',
    viewAll: 'सभी देखें',
    refresh: 'रीफ्रेश',
    totalArticles: 'कुल लेख',
    categories: 'श्रेणियां',
    languages: 'भाषाएं',
    realTimeUpdates: 'रियल-टाइम अपडेट',
    newsPortal: 'समाचार पोर्टल',
    todaysNews: 'आज की खबरें',
    localNews: 'स्थानीय समाचार',
    nationalNews: 'राष्ट्रीय समाचार',
    internationalNews: 'अंतर्राष्ट्रीय समाचार',
    exclusiveReport: 'विशेष रिपोर्ट',
    liveReporting: 'लाइव रिपोर्टिंग',
    newsAlert: 'समाचार अलर्ट',
    pressRelease: 'प्रेस विज्ञप्ति',
    editorial: 'संपादकीय',
    opinion: 'राय',
    analysis: 'विश्लेषण',
    interview: 'साक्षात्कार',
    photoStory: 'फोटो स्टोरी',
    videoNews: 'वीडियो समाचार',
    podcast: 'पॉडकास्ट',
    newsletter: 'न्यूज़लेटर'
  },
  or: {
    home: 'ଘର',
    india: 'ଭାରତ',
    world: 'ବିଶ୍ୱ',
    business: 'ବ୍ୟବସାୟ',
    technology: 'ପ୍ରଯୁକ୍ତି',
    sports: 'ଖେଳ',
    entertainment: 'ମନୋରଞ୍ଜନ',
    health: 'ସ୍ୱାସ୍ଥ୍ୟ',
    breakingNews: 'ତାଜା ଖବର',
    featuredStories: 'ମୁଖ୍ୟ ସମାଚାର',
    searchPlaceholder: 'ସମାଚାର ଖୋଜନ୍ତୁ...',
    readMore: 'ଅଧିକ ପଢ଼ନ୍ତୁ',
    readFull: 'ସମ୍ପୂର୍ଣ୍ଣ ଲେଖ ପଢ଼ନ୍ତୁ',
    listen: 'ଶୁଣନ୍ତୁ',
    share: 'ସେୟାର କରନ୍ତୁ',
    loading: 'ନୂତନ ସମାଚାର ଲୋଡ୍ ହେଉଛି...',
    noArticles: 'କୌଣସି ଲେଖ ମିଳିଲା ନାହିଁ',
    askQuestion: 'କୌଣସି ସମାଚାର ବିଷୟରେ ପଚାରନ୍ତୁ...',
    chatWithAI: 'AI ସହାୟକଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ',
    liveUpdates: 'ଲାଇଭ୍ ଅପଡେଟ୍',
    premiumContent: 'ପ୍ରିମିୟମ୍ ବିଷୟବସ୍ତୁ',
    freeContent: 'ମାଗଣା ପ୍ରବେଶ',
    trending: 'ଟ୍ରେଣ୍ଡିଂ',
    latest: 'ନବୀନତମ ସମାଚାର',
    author: 'ଲେଖକ',
    source: 'ଉତ୍ସ',
    publishedOn: 'ପ୍ରକାଶିତ',
    readTime: 'ମିନିଟ୍ ପଢ଼ନ୍ତୁ',
    tags: 'ଟ୍ୟାଗ୍',
    relatedNews: 'ସମ୍ବନ୍ଧୀତ ସମାଚାର',
    viewAll: 'ସବୁ ଦେଖନ୍ତୁ',
    refresh: 'ରିଫ୍ରେସ୍',
    totalArticles: 'ମୋଟ ଲେଖ',
    categories: 'ବର୍ଗ',
    languages: 'ଭାଷା',
    realTimeUpdates: 'ରିଅଲ୍-ଟାଇମ୍ ଅପଡେଟ୍',
    newsPortal: 'ସମାଚାର ପୋର୍ଟାଲ୍',
    todaysNews: 'ଆଜିର ଖବର',
    localNews: 'ସ୍ଥାନୀୟ ସମାଚାର',
    nationalNews: 'ଜାତୀୟ ସମାଚାର',
    internationalNews: 'ଆନ୍ତର୍ଜାତିକ ସମାଚାର',
    exclusiveReport: 'ବିଶେଷ ରିପୋର୍ଟ',
    liveReporting: 'ଲାଇଭ୍ ରିପୋର୍ଟିଂ',
    newsAlert: 'ସମାଚାର ଆଲର୍ଟ',
    pressRelease: 'ପ୍ରେସ୍ ରିଲିଜ୍',
    editorial: 'ସମ୍ପାଦକୀୟ',
    opinion: 'ମତାମତ',
    analysis: 'ବିଶ୍ଳେଷଣ',
    interview: 'ସାକ୍ଷାତକାର',
    photoStory: 'ଫଟୋ ଷ୍ଟୋରୀ',
    videoNews: 'ଭିଡିଓ ସମାଚାର',
    podcast: 'ପୋଡକାଷ୍ଟ',
    newsletter: 'ନ୍ୟୁଜଲେଟର'
  },
  bn: {
    home: 'হোম',
    india: 'ভারত',
    world: 'বিশ্ব',
    business: 'ব্যবসা',
    technology: 'প্রযুক্তি',
    sports: 'খেলা',
    entertainment: 'বিনোদন',
    health: 'স্বাস্থ্য',
    breakingNews: 'সর্বশেষ খবর',
    featuredStories: 'প্রধান সংবাদ',
    searchPlaceholder: 'সংবাদ খুঁজুন...',
    readMore: 'আরও পড়ুন',
    readFull: 'সম্পূর্ণ নিবন্ধ পড়ুন',
    listen: 'শুনুন',
    share: 'শেয়ার করুন',
    loading: 'সর্বশেষ সংবাদ লোড হচ্ছে...',
    noArticles: 'কোনো নিবন্ধ পাওয়া যায়নি',
    askQuestion: 'যেকোনো সংবাদ বিষয়ে জিজ্ঞাসা করুন...',
    chatWithAI: 'AI সহায়কের সাথে কথা বলুন',
    liveUpdates: 'লাইভ আপডেট',
    premiumContent: 'প্রিমিয়াম কন্টেন্ট',
    freeContent: 'বিনামূল্যে অ্যাক্সেস',
    trending: 'ট্রেন্ডিং',
    latest: 'সর্বশেষ সংবাদ',
    author: 'লেখক',
    source: 'উৎস',
    publishedOn: 'প্রকাশিত',
    readTime: 'মিনিট পড়ুন',
    tags: 'ট্যাগ',
    relatedNews: 'সম্পর্কিত সংবাদ',
    viewAll: 'সব দেখুন',
    refresh: 'রিফ্রেশ',
    totalArticles: 'মোট নিবন্ধ',
    categories: 'বিভাগ',
    languages: 'ভাষা',
    realTimeUpdates: 'রিয়েল-টাইম আপডেট',
    newsPortal: 'সংবাদ পোর্টাল',
    todaysNews: 'আজকের খবর',
    localNews: 'স্থানীয় সংবাদ',
    nationalNews: 'জাতীয় সংবাদ',
    internationalNews: 'আন্তর্জাতিক সংবাদ',
    exclusiveReport: 'একচেটিয়া রিপোর্ট',
    liveReporting: 'লাইভ রিপোর্টিং',
    newsAlert: 'সংবাদ সতর্কতা',
    pressRelease: 'প্রেস রিলিজ',
    editorial: 'সম্পাদকীয়',
    opinion: 'মতামত',
    analysis: 'বিশ্লেষণ',
    interview: 'সাক্ষাৎকার',
    photoStory: 'ফটো স্টোরি',
    videoNews: 'ভিডিও সংবাদ',
    podcast: 'পডকাস্ট',
    newsletter: 'নিউজলেটার'
  },
  ta: {
    home: 'முகப்பு',
    india: 'இந்தியா',
    world: 'உலகம்',
    business: 'வணிகம்',
    technology: 'தொழில்நுட்பம்',
    sports: 'விளையாட்டு',
    entertainment: 'பொழுதுபோக்கு',
    health: 'சுகாதாரம்',
    breakingNews: 'சமீபத்திய செய்திகள்',
    featuredStories: 'முக்கிய செய்திகள்',
    searchPlaceholder: 'செய்திகளைத் தேடுங்கள்...',
    readMore: 'மேலும் படிக்க',
    readFull: 'முழு கட்டுரையைப் படிக்க',
    listen: 'கேளுங்கள்',
    share: 'பகிருங்கள்',
    loading: 'சமீபத்திய செய்திகள் ஏற்றப்படுகின்றன...',
    noArticles: 'கட்டுரைகள் எதுவும் கிடைக்கவில்லை',
    askQuestion: 'எந்த செய்தி தலைப்பைப் பற்றியும் கேளுங்கள்...',
    chatWithAI: 'AI உதவியாளருடன் பேசுங்கள்',
    liveUpdates: 'நேரடி புதுப்பிப்புகள்',
    premiumContent: 'பிரீமியம் உள்ளடக்கம்',
    freeContent: 'இலவச அணுகல்',
    trending: 'டிரெண்டிங்',
    latest: 'சமீபத்திய செய்திகள்',
    author: 'ஆசிரியர்',
    source: 'மூலம்',
    publishedOn: 'வெளியிடப்பட்டது',
    readTime: 'நிமிடம் படிக்க',
    tags: 'குறிச்சொற்கள்',
    relatedNews: 'தொடர்புடைய செய்திகள்',
    viewAll: 'அனைத்தையும் பார்க்க',
    refresh: 'புதுப்பிக்க',
    totalArticles: 'மொத்த கட்டுரைகள்',
    categories: 'வகைகள்',
    languages: 'மொழிகள்',
    realTimeUpdates: 'நிகழ்நேர புதுப்பிப்புகள்',
    newsPortal: 'செய்தி போர்ட்டல்',
    todaysNews: 'இன்றைய செய்திகள்',
    localNews: 'உள்ளூர் செய்திகள்',
    nationalNews: 'தேசிய செய்திகள்',
    internationalNews: 'சர்வதேச செய்திகள்',
    exclusiveReport: 'பிரத்யேக அறிக்கை',
    liveReporting: 'நேரடி அறிக்கை',
    newsAlert: 'செய்தி எச்சரிக்கை',
    pressRelease: 'பத்திரிகை வெளியீடு',
    editorial: 'தலையங்கம்',
    opinion: 'கருத்து',
    analysis: 'பகுப்பாய்வு',
    interview: 'நேர்காணல்',
    photoStory: 'புகைப்பட கதை',
    videoNews: 'வீடியோ செய்திகள்',
    podcast: 'பாட்காஸ்ட்',
    newsletter: 'செய்திமடல்'
  },
  te: {
    home: 'హోమ్',
    india: 'భారతదేశం',
    world: 'ప్రపంచం',
    business: 'వ్యాపారం',
    technology: 'సాంకేతికత',
    sports: 'క్రీడలు',
    entertainment: 'వినోదం',
    health: 'ఆరోగ్యం',
    breakingNews: 'తాజా వార్తలు',
    featuredStories: 'ప్రధాన వార్తలు',
    searchPlaceholder: 'వార్తలను వెతకండి...',
    readMore: 'మరింత చదవండి',
    readFull: 'పూర్తి కథనం చదవండి',
    listen: 'వినండి',
    share: 'షేర్ చేయండి',
    loading: 'తాజా వార్తలు లోడ్ అవుతున్నాయి...',
    noArticles: 'కథనాలు కనుగొనబడలేదు',
    askQuestion: 'ఏదైనా వార్తా అంశం గురించి అడగండి...',
    chatWithAI: 'AI సహాయకుడితో మాట్లాడండి',
    liveUpdates: 'లైవ్ అప్‌డేట్‌లు',
    premiumContent: 'ప్రీమియం కంటెంట్',
    freeContent: 'ఉచిత యాక్సెస్',
    trending: 'ట్రెండింగ్',
    latest: 'తాజా వార్తలు',
    author: 'రచయిత',
    source: 'మూలం',
    publishedOn: 'ప్రచురించబడింది',
    readTime: 'నిమిషాలు చదవండి',
    tags: 'ట్యాగ్‌లు',
    relatedNews: 'సంబంధిత వార్తలు',
    viewAll: 'అన్నీ చూడండి',
    refresh: 'రిఫ్రెష్',
    totalArticles: 'మొత్తం కథనాలు',
    categories: 'వర్గాలు',
    languages: 'భాషలు',
    realTimeUpdates: 'రియల్-టైమ్ అప్‌డేట్‌లు',
    newsPortal: 'వార్తా పోర్టల్',
    todaysNews: 'నేటి వార్తలు',
    localNews: 'స్థానిక వార్తలు',
    nationalNews: 'జాతీయ వార్తలు',
    internationalNews: 'అంతర్జాతీయ వార్తలు',
    exclusiveReport: 'ప్రత్యేక నివేదిక',
    liveReporting: 'లైవ్ రిపోర్టింగ్',
    newsAlert: 'వార్తా హెచ్చరిక',
    pressRelease: 'పత్రికా ప్రకటన',
    editorial: 'సంపాదకీయం',
    opinion: 'అభిప్రాయం',
    analysis: 'విశ్లేషణ',
    interview: 'ఇంటర్వ్యూ',
    photoStory: 'ఫోటో స్టోరీ',
    videoNews: 'వీడియో వార్తలు',
    podcast: 'పాడ్‌కాస్ట్',
    newsletter: 'న్యూస్‌లెటర్'
  },
  gu: {
    home: 'હોમ',
    india: 'ભારત',
    world: 'વિશ્વ',
    business: 'વ્યવસાય',
    technology: 'ટેકનોલોજી',
    sports: 'રમતગમત',
    entertainment: 'મનોરંજન',
    health: 'આરોગ્ય',
    breakingNews: 'તાજા સમાચાર',
    featuredStories: 'મુખ્ય સમાચાર',
    searchPlaceholder: 'સમાચાર શોધો...',
    readMore: 'વધુ વાંચો',
    readFull: 'સંપૂર્ણ લેખ વાંચો',
    listen: 'સાંભળો',
    share: 'શેર કરો',
    loading: 'તાજા સમાચાર લોડ થઈ રહ્યા છે...',
    noArticles: 'કોઈ લેખ મળ્યો નથી',
    askQuestion: 'કોઈપણ સમાચાર વિષય વિશે પૂછો...',
    chatWithAI: 'AI સહાયક સાથે વાત કરો',
    liveUpdates: 'લાઈવ અપડેટ્સ',
    premiumContent: 'પ્રીમિયમ કન્ટેન્ટ',
    freeContent: 'મફત એક્સેસ',
    trending: 'ટ્રેન્ડિંગ',
    latest: 'તાજા સમાચાર',
    author: 'લેખક',
    source: 'સ્રોત',
    publishedOn: 'પ્રકાશિત',
    readTime: 'મિનિટ વાંચો',
    tags: 'ટેગ્સ',
    relatedNews: 'સંબંધિત સમાચાર',
    viewAll: 'બધું જુઓ',
    refresh: 'રિફ્રેશ',
    totalArticles: 'કુલ લેખો',
    categories: 'કેટેગરીઝ',
    languages: 'ભાષાઓ',
    realTimeUpdates: 'રિયલ-ટાઈમ અપડેટ્સ',
    newsPortal: 'સમાચાર પોર્ટલ',
    todaysNews: 'આજના સમાચાર',
    localNews: 'સ્થાનિક સમાચાર',
    nationalNews: 'રાષ્ટ્રીય સમાચાર',
    internationalNews: 'આંતરરાષ્ટ્રીય સમાચાર',
    exclusiveReport: 'વિશેષ રિપોર્ટ',
    liveReporting: 'લાઈવ રિપોર્ટિંગ',
    newsAlert: 'સમાચાર અલર્ટ',
    pressRelease: 'પ્રેસ રિલીઝ',
    editorial: 'સંપાદકીય',
    opinion: 'અભિપ્રાય',
    analysis: 'વિશ્લેષણ',
    interview: 'ઇન્ટરવ્યુ',
    photoStory: 'ફોટો સ્ટોરી',
    videoNews: 'વિડિયો સમાચાર',
    podcast: 'પોડકાસ્ટ',
    newsletter: 'ન્યૂઝલેટર'
  },
  mr: {
    home: 'मुख्यपृष्ठ',
    india: 'भारत',
    world: 'जग',
    business: 'व्यवसाय',
    technology: 'तंत्रज्ञान',
    sports: 'क्रीडा',
    entertainment: 'मनोरंजन',
    health: 'आरोग्य',
    breakingNews: 'ताज्या बातम्या',
    featuredStories: 'मुख्य बातम्या',
    searchPlaceholder: 'बातम्या शोधा...',
    readMore: 'अधिक वाचा',
    readFull: 'संपूर्ण लेख वाचा',
    listen: 'ऐका',
    share: 'शेअर करा',
    loading: 'ताज्या बातम्या लोड होत आहेत...',
    noArticles: 'कोणतेही लेख सापडले नाहीत',
    askQuestion: 'कोणत्याही बातमी विषयाबद्दल विचारा...',
    chatWithAI: 'AI सहाय्यकाशी बोला',
    liveUpdates: 'लाइव्ह अपडेट्स',
    premiumContent: 'प्रीमियम सामग्री',
    freeContent: 'मोफत प्रवेश',
    trending: 'ट्रेंडिंग',
    latest: 'ताज्या बातम्या',
    author: 'लेखक',
    source: 'स्रोत',
    publishedOn: 'प्रकाशित',
    readTime: 'मिनिटे वाचा',
    tags: 'टॅग्स',
    relatedNews: 'संबंधित बातम्या',
    viewAll: 'सर्व पहा',
    refresh: 'रिफ्रेश',
    totalArticles: 'एकूण लेख',
    categories: 'श्रेणी',
    languages: 'भाषा',
    realTimeUpdates: 'रिअल-टाइम अपडेट्स',
    newsPortal: 'बातमी पोर्टल',
    todaysNews: 'आजच्या बातम्या',
    localNews: 'स्थानिक बातम्या',
    nationalNews: 'राष्ट्रीय बातम्या',
    internationalNews: 'आंतरराष्ट्रीय बातम्या',
    exclusiveReport: 'विशेष अहवाल',
    liveReporting: 'लाइव्ह रिपोर्टिंग',
    newsAlert: 'बातमी अलर्ट',
    pressRelease: 'प्रेस रिलीज',
    editorial: 'संपादकीय',
    opinion: 'मत',
    analysis: 'विश्लेषण',
    interview: 'मुलाखत',
    photoStory: 'फोटो स्टोरी',
    videoNews: 'व्हिडिओ बातम्या',
    podcast: 'पॉडकास्ट',
    newsletter: 'न्यूजलेटर'
  },
  kn: {
    home: 'ಮುಖ್ಯಪುಟ',
    india: 'ಭಾರತ',
    world: 'ಪ್ರಪಂಚ',
    business: 'ವ್ಯಾಪಾರ',
    technology: 'ತಂತ್ರಜ್ಞಾನ',
    sports: 'ಕ್ರೀಡೆ',
    entertainment: 'ಮನರಂಜನೆ',
    health: 'ಆರೋಗ್ಯ',
    breakingNews: 'ತಾಜಾ ಸುದ್ದಿ',
    featuredStories: 'ಮುಖ್ಯ ಸುದ್ದಿ',
    searchPlaceholder: 'ಸುದ್ದಿ ಹುಡುಕಿ...',
    readMore: 'ಹೆಚ್ಚು ಓದಿ',
    readFull: 'ಸಂಪೂರ್ಣ ಲೇಖನ ಓದಿ',
    listen: 'ಕೇಳಿ',
    share: 'ಹಂಚಿಕೊಳ್ಳಿ',
    loading: 'ತಾಜಾ ಸುದ್ದಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noArticles: 'ಯಾವುದೇ ಲೇಖನಗಳು ಸಿಗಲಿಲ್ಲ',
    askQuestion: 'ಯಾವುದೇ ಸುದ್ದಿ ವಿಷಯದ ಬಗ್ಗೆ ಕೇಳಿ...',
    chatWithAI: 'AI ಸಹಾಯಕರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    liveUpdates: 'ಲೈವ್ ಅಪ್‌ಡೇಟ್‌ಗಳು',
    premiumContent: 'ಪ್ರೀಮಿಯಂ ವಿಷಯ',
    freeContent: 'ಉಚಿತ ಪ್ರವೇಶ',
    trending: 'ಟ್ರೆಂಡಿಂಗ್',
    latest: 'ತಾಜಾ ಸುದ್ದಿ',
    author: 'ಲೇಖಕ',
    source: 'ಮೂಲ',
    publishedOn: 'ಪ್ರಕಟಿಸಲಾಗಿದೆ',
    readTime: 'ನಿಮಿಷ ಓದಿ',
    tags: 'ಟ್ಯಾಗ್‌ಗಳು',
    relatedNews: 'ಸಂಬಂಧಿತ ಸುದ್ದಿ',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    refresh: 'ರಿಫ್ರೆಶ್',
    totalArticles: 'ಒಟ್ಟು ಲೇಖನಗಳು',
    categories: 'ವರ್ಗಗಳು',
    languages: 'ಭಾಷೆಗಳು',
    realTimeUpdates: 'ರಿಯಲ್-ಟೈಮ್ ಅಪ್‌ಡೇಟ್‌ಗಳು',
    newsPortal: 'ಸುದ್ದಿ ಪೋರ್ಟಲ್',
    todaysNews: 'ಇಂದಿನ ಸುದ್ದಿ',
    localNews: 'ಸ್ಥಳೀಯ ಸುದ್ದಿ',
    nationalNews: 'ರಾಷ್ಟ್ರೀಯ ಸುದ್ದಿ',
    internationalNews: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಸುದ್ದಿ',
    exclusiveReport: 'ವಿಶೇಷ ವರದಿ',
    liveReporting: 'ಲೈವ್ ರಿಪೋರ್ಟಿಂಗ್',
    newsAlert: 'ಸುದ್ದಿ ಎಚ್ಚರಿಕೆ',
    pressRelease: 'ಪತ್ರಿಕಾ ಪ್ರಕಟಣೆ',
    editorial: 'ಸಂಪಾದಕೀಯ',
    opinion: 'ಅಭಿಪ್ರಾಯ',
    analysis: 'ವಿಶ್ಲೇಷಣೆ',
    interview: 'ಸಂದರ್ಶನ',
    photoStory: 'ಫೋಟೋ ಸ್ಟೋರಿ',
    videoNews: 'ವೀಡಿಯೋ ಸುದ್ದಿ',
    podcast: 'ಪಾಡ್‌ಕಾಸ್ಟ್',
    newsletter: 'ನ್ಯೂಸ್‌ಲೆಟರ್'
  },
  pa: {
    home: 'ਘਰ',
    india: 'ਭਾਰਤ',
    world: 'ਸੰਸਾਰ',
    business: 'ਕਾਰੋਬਾਰ',
    technology: 'ਤਕਨਾਲੋਜੀ',
    sports: 'ਖੇਡਾਂ',
    entertainment: 'ਮਨੋਰੰਜਨ',
    health: 'ਸਿਹਤ',
    breakingNews: 'ਤਾਜ਼ਾ ਖਬਰਾਂ',
    featuredStories: 'ਮੁੱਖ ਖਬਰਾਂ',
    searchPlaceholder: 'ਖਬਰਾਂ ਖੋਜੋ...',
    readMore: 'ਹੋਰ ਪੜ੍ਹੋ',
    readFull: 'ਪੂਰਾ ਲੇਖ ਪੜ੍ਹੋ',
    listen: 'ਸੁਣੋ',
    share: 'ਸਾਂਝਾ ਕਰੋ',
    loading: 'ਤਾਜ਼ਾ ਖਬਰਾਂ ਲੋਡ ਹੋ ਰਹੀਆਂ ਹਨ...',
    noArticles: 'ਕੋਈ ਲੇਖ ਨਹੀਂ ਮਿਲਿਆ',
    askQuestion: 'ਕਿਸੇ ਵੀ ਖਬਰ ਦੇ ਵਿਸ਼ੇ ਬਾਰੇ ਪੁੱਛੋ...',
    chatWithAI: 'AI ਸਹਾਇਕ ਨਾਲ ਗੱਲ ਕਰੋ',
    liveUpdates: 'ਲਾਈਵ ਅਪਡੇਟਸ',
    premiumContent: 'ਪ੍ਰੀਮੀਅਮ ਸਮੱਗਰੀ',
    freeContent: 'ਮੁਫਤ ਪਹੁੰਚ',
    trending: 'ਟ੍ਰੈਂਡਿੰਗ',
    latest: 'ਤਾਜ਼ਾ ਖਬਰਾਂ',
    author: 'ਲੇਖਕ',
    source: 'ਸਰੋਤ',
    publishedOn: 'ਪ੍ਰਕਾਸ਼ਿਤ',
    readTime: 'ਮਿੰਟ ਪੜ੍ਹੋ',
    tags: 'ਟੈਗਸ',
    relatedNews: 'ਸੰਬੰਧਿਤ ਖਬਰਾਂ',
    viewAll: 'ਸਭ ਦੇਖੋ',
    refresh: 'ਰਿਫਰੈਸ਼',
    totalArticles: 'ਕੁੱਲ ਲੇਖ',
    categories: 'ਸ਼੍ਰੇਣੀਆਂ',
    languages: 'ਭਾਸ਼ਾਵਾਂ',
    realTimeUpdates: 'ਰੀਅਲ-ਟਾਈਮ ਅਪਡੇਟਸ',
    newsPortal: 'ਖਬਰਾਂ ਪੋਰਟਲ',
    todaysNews: 'ਅੱਜ ਦੀਆਂ ਖਬਰਾਂ',
    localNews: 'ਸਥਾਨਕ ਖਬਰਾਂ',
    nationalNews: 'ਰਾਸ਼ਟਰੀ ਖਬਰਾਂ',
    internationalNews: 'ਅੰਤਰਰਾਸ਼ਟਰੀ ਖਬਰਾਂ',
    exclusiveReport: 'ਵਿਸ਼ੇਸ਼ ਰਿਪੋਰਟ',
    liveReporting: 'ਲਾਈਵ ਰਿਪੋਰਟਿੰਗ',
    newsAlert: 'ਖਬਰ ਅਲਰਟ',
    pressRelease: 'ਪ੍ਰੈਸ ਰਿਲੀਜ਼',
    editorial: 'ਸੰਪਾਦਕੀ',
    opinion: 'ਰਾਏ',
    analysis: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    interview: 'ਇੰਟਰਵਿਊ',
    photoStory: 'ਫੋਟੋ ਸਟੋਰੀ',
    videoNews: 'ਵੀਡੀਓ ਖਬਰਾਂ',
    podcast: 'ਪੌਡਕਾਸਟ',
    newsletter: 'ਨਿਊਜ਼ਲੈਟਰ'
  }
};

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (lang: string) => void;
  languages: Language[];
  translate: (key: string) => string;
  getLanguageScript: (langCode: string) => string;
  getRegionalContext: (langCode: string) => string;
  translations: Record<string, string>;
  translateContent: (content: string, targetLanguage: string) => string;
  getLanguageDirection: (langCode: string) => 'ltr' | 'rtl';
  getCulturalContext: (langCode: string) => { region: string; script: string; direction: 'ltr' | 'rtl' };
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('cambliss-language');
    if (savedLanguage && languages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
      // Apply script-specific CSS class to body
      const language = languages.find(lang => lang.code === savedLanguage);
      if (language) {
        document.body.className = document.body.className.replace(/script-\w+/g, '');
        document.body.classList.add(`script-${language.script.toLowerCase()}`);
        document.documentElement.dir = language.direction;
      }
    }
  }, []);

  const setLanguage = (lang: string) => {
    setCurrentLanguage(lang);
    localStorage.setItem('cambliss-language', lang);
    
    // Apply script-specific styling and direction
    const language = languages.find(l => l.code === lang);
    if (language) {
      document.body.className = document.body.className.replace(/script-\w+/g, '');
      document.body.classList.add(`script-${language.script.toLowerCase()}`);
      document.documentElement.dir = language.direction;
    }
  };

  const translate = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const translateContent = (content: string, targetLanguage: string): string => {
    // In a real implementation, this would call a translation API
    // For now, we'll return the original content with a note that it would be translated
    if (targetLanguage === 'en') return content;
    
    // Mock translation - in production, integrate with Google Translate API or similar
    const languageNames: Record<string, string> = {
      'hi': 'हिन्दी',
      'or': 'ଓଡ଼ିଆ',
      'bn': 'বাংলা',
      'ta': 'தமிழ்',
      'te': 'తెలుగు',
      'gu': 'ગુજરાતી',
      'mr': 'मराठी',
      'kn': 'ಕನ್ನಡ',
      'pa': 'ਪੰਜਾਬੀ'
    };
    
    return content; // In production, this would return translated content
  };
  const getLanguageScript = (langCode: string): string => {
    const language = languages.find(lang => lang.code === langCode);
    return language?.script || 'Latin';
  };

  const getRegionalContext = (langCode: string): string => {
    const language = languages.find(lang => lang.code === langCode);
    return language?.region || 'Global';
  };

  const getLanguageDirection = (langCode: string): 'ltr' | 'rtl' => {
    const language = languages.find(lang => lang.code === langCode);
    return language?.direction || 'ltr';
  };

  const getCulturalContext = (langCode: string) => {
    const language = languages.find(lang => lang.code === langCode);
    return {
      region: language?.region || 'Global',
      script: language?.script || 'Latin',
      direction: language?.direction || 'ltr'
    };
  };
  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      setLanguage,
      languages,
      translate,
      getLanguageScript,
      getRegionalContext,
      translations: translations[currentLanguage] || translations.en,
      translateContent,
      getLanguageDirection,
      getCulturalContext
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};